trigger:
- main

variables:
  user_email: "lucasvinicius7000@gmail.com"
  user_name: "lucasvinicius7000"
  githubtoken: "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"

steps:
- checkout: self
- script: |
    git clone https://lucasvinicius7000:6h7bm4y5dpg4ybd6o5nolpgw7xlrltnbwmdqkzkaknh3cocshnba@dev.azure.com/lucasvinicius7000/PI%20VII/_git/PI-VII-Web
    cd PI-VII-Web
    git config user.email "$(user_email)"
    git config user.name "$(user_name)"
    git remote set-url origin https://$(githubtoken)@github.com/LucasVinicius7000/PI-VII-Web.git
    git push origin main -f
  displayName: 'Sync with GitHub'
