

trigger:
- main

variables:
  user_email: "lucasvinicius7000@gmail.com"
  user_name: "lucasvinicius7000"
  githubtoken: "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"

steps:
- checkout: self
- script: |
    git clone https://lucasvinicius7000:jl253awuypgg6cpjt353by3y3sodq4m3e4dfz7nx7ydl2dhishuq@dev.azure.com/lucasvinicius7000/PI%20VII/_git/PI-VII-Web
    cd PI-VII-Web
    git config user.email "$(user_email)"
    git config user.name "$(user_name)"
    git remote set-url origin https://$(githubtoken)@github.com/LucasVinicius7000/PI-VII-Web.git
    git push origin main -f
  displayName: 'Sync with GitHub'
